### ISSUE TITLE
Unable to list filename without directory slash in .vtt file

### ISSUE THREAD

**Issue by philipgoyal** [pysnippet/thumbnails#65]
I would like .vtt entries to look like this:

00:00:00.000 --> 00:00:05.000
video.png#xywh=0,0,384,216

i.e. the .png file is referred to directly, not prepended with anything.

But if I choose generator.base = "", then the filename is prepended with generator.output.

And if I choose generator.base = " ", then the filename appears as:

 \video.png#xywh=0,0,384,216

Could you fix this?

Many thanks!

**Comment by ArtyomVancyan** [comment]
Hi @philipgoyal, thanks for the report.

It is because the run directory depends on the path calculation. It uses paths relative to the running directory. So you can just run the script or CLI from the directory where the video is.

Thanks, I hope this fixes your issue.

**Comment by philipgoyal** [comment]
Thanks for your reply, Artyom.  If I run the script pointing to the input file, and simply omit the generator.base and generator.output variables, then the .vtt file automatically includes the actual filesystem path to the video.png file.  And, as I say, I don't want that—I'll be moving the .vtt file to a website, where the .png file will be in the same directory, so there is no need for a full path. 

So could you perhaps introduce a flag that allows this behaviour to be user-selected?

**Comment by ArtyomVancyan** [comment]
Sorry @philipgoyal, for the misunderstanding. It is my fault for not having a proper issue template requiring the things you've tried, your expectations, and the actual result. Yes, the `output` value matters in calculating the thumbnail path in the `.vtt`. It is just the directory path where the generated files should be placed, and the `base` is the URI prefix as described in the `thumbnails -h` result, and it overrides the path prefix even if `output` is set.

If the above information doesn't solve your issue and you still have any questions, please answer these questions as detailed as possible.

 - Are you using the CLI version or the Python package?
 - How do your files' paths relate to each other? (please provide the files tree, including the videos and the script if you use the Python package, otherwise the path where the command is run)
- Expected result in a few lines.
- Actual result in a few lines.

Please do not hesitate to ask questions about the non-mentioned cases if there are some. I will wait for you to reply.

**Comment by philipgoyal** [comment]
Many thanks for your detailed reply.

First, I am using the Python package rather than the CLI.  That suits my needs better.

Second, the video is a folder, and has path "/path_to_video_folder/video.mp4".

Third, the desired result is that the .png and .vtt files are written to the folder "/path_to_video_folder".  And that the .vtt file contains lines of the form:

00:00:00.000 --> 00:00:05.000
video.png#xywh=0,0,384,216

Fourth, when I set the variable generator.base = "", then the actual .vtt file contains lines of the form:

00:00:00.000 --> 00:00:05.000
/path_to_video_folder/video.png#xywh=0,0,384,216

(i.e. the file path of the input video is not removed).

If I instead set the variable generator.base = " ", then the .vtt file contains lines of the form:

00:00:00.000 --> 00:00:05.000
 /video.png#xywh=0,0,384,216

i.e. a space followed by '/' are prepended to video.png

I hope this helps clarify the situation.  What I would hope is that setting generator.base = "" would lead to .vtt omitting any reference to the directory in which "video.png" is located.

**Comment by ArtyomVancyan** [comment]
Hey @philipgoyal, check out the latest release by `pip install --upgrade thumbnails` and try to set the `base` to an empty string. It works for me. Please verify if it works for you as well.

**Comment by philipgoyal** [comment]
Thank you @ArtyomVancyan—it works perfectly.  i.e. setting generator.base = "" now creates a .vtt file which references video.png without prepending it with path information.

**Comment by philipgoyal** [comment]
I've closed the issue as it has been resolved by the update.
